### ISSUE TITLE
Lambda update-code command error

### ISSUE THREAD

**Issue by ghost** [raphaelbh/lambda-local#1]
I am trying to run below commands, it's displayed this type of message "Could not connect to the endpoint URL: "

$ lambda update-code 'lambda'

Could not connect to the endpoint URL: "http://localhost:4566/2015-03-31/functions/lambda/code"

$

**Comment by raphaelbh** [comment]
This problem is happening because you didn't create the resources using localstack (https://localstack.cloud/).

I've updated the example making it easier to create the resource.

https://github.com/raphaelbh/lambda-local/tree/main/sample
